Repository arthur91f/exeiac, pull requests merged in 2022-12, with the labels that each got.

#42 Fix/display debug infra
  src/actions/common.go
  src/actions/debugActions.go
  src/infra/bricks.go
Labels: bug

#47 feat: implement module execution for basic actions
  example/repos/modules/module_test.sh
  src/actions/common.go
  src/actions/default.go
  src/go.mod
  src/go.sum
  src/infra/module.go
  src/main.go
Labels: enhancement

#49 feat: enable storage of a Cmd output and std redirection
  src/actions/common.go
  src/actions/default.go
  src/infra/module.go
Labels: enhancement

#48 Feat/generate inputs
  example/repos/modules/module_test.sh
  src/infra/brick.go
Labels: enhancement

#55 refacto: return path when generating a file
  src/infra/brick.go
Labels: refactoring

#61 feat: simplify the formatter definition to better fit its usage
  src/actions/common.go
  src/infra/brick.go
  src/infra/formatters.go
Labels: enhancement

#63 feat: implement JSON Formatter
  src/infra/formatters.go
Labels: enhancement

#64 feat: type and validate a brick's input format
  src/infra/brick.go
  src/infra/formatters.go
Labels: enhancement

#68 Refacto/use flag package
  example/exeiac.yml
  example/repos/infra-grounds/2-envs/1-production/1-network/brick.yml
  example/repos/infra-grounds/2-envs/1-production/2-bastion/brick.yml
  example/repos/infra-grounds/2-envs/1-staging/1-network/brick.yml
  example/repos/infra-grounds/2-envs/1-staging/2-bastion/brick.yml
  example/repos/infra-grounds/2-envs/2-monitoring/1-network/brick.yml
  example/repos/infra-grounds/2-envs/2-monitoring/2-bastion/brick.yml
  src/actions/clean.go
  src/actions/common.go
  src/actions/debugActions.go
  src/actions/default.go
  src/actions/help.go
  src/actions/lay.go
  src/actions/plan.go
  src/actions/remove.go
  src/actions/show.go
  src/arguments/arguments.go
  src/arguments/configuration.go
  src/arguments/consume_args.go
  src/arguments/set_args_with_conf_files.go
  src/arguments/types_and_vars.go
  src/go.mod
  src/go.sum
  src/infra/error.go
  src/infra/infra.go
  src/main.go
  src/tools/stringSlice.go
Labels: enhancement

#71 Feat/add show usage
  src/actions/common.go
  src/actions/debugActions.go
  src/actions/default.go
  src/actions/help.go
  src/actions/plan.go
  src/arguments/arguments.go
  src/arguments/configuration.go
  src/arguments/flags.go
  src/infra/brick.go
  src/infra/bricks.go
  src/infra/infra.go
  src/infra/module.go
  src/main.go
Labels: enhancement

#72 Feat/xdg configuration
  src/arguments/configuration.go
  src/go.mod
  src/go.sum
  src/main.go
Labels: enhancement

#73 fix: don't panic when there is no arg
  src/main.go
Labels: bug

#74 feat(brick/resolveDeps): enrich error message
  src/infra/brick.go
Labels: enhancement, good first issue

#75 feat: enable local module
  src/infra/brick.go
  src/infra/infra.go
Labels: enhancement

#76 fix(action): manage module exit code
  src/actions/lay.go
  src/actions/plan.go
  src/actions/remove.go
  src/infra/module.go
Labels: bug

#77 fix: pass other options and non-interactive
  src/actions/lay.go
  src/actions/plan.go
  src/actions/remove.go
  src/arguments/configuration.go
Labels: bug
