Repository arthur91f/exeiac, pull requests merged in 2023-01, with the labels that each got.

#86 Refacto/misc
  src/actions/default.go
  src/actions/lay.go
  src/actions/plan.go
  src/actions/remove.go
  src/actions/show.go
  src/arguments/configuration.go
  src/infra/infra.go
Labels: refactoring

#103 fix(arguments): fix format flag
  src/arguments/arguments.go
  src/arguments/flags.go
Labels: bug

#104 feat(brick): log when resolve deps failed
  src/infra/brick.go
Labels: enhancement

#88 Feat/auto completion
  src/arguments/arguments.go
  src/arguments/configuration.go
  src/arguments/flags.go
  src/completion/README.md
  src/completion/completion.go
  src/completion/scripts/exeiac.fish
  src/completion/scripts/exeiac.sh
  src/completion/scripts/exeiac.zsh
  src/main.go
Labels: enhancement

#107 feat(action/clean): implement it
  src/actions/clean.go
  src/actions/common.go
Labels: enhancement

#108 feat(infra): improve enrich err msg
  src/infra/infra.go
  src/infra/module.go
Labels: enhancement

#109 Fix/handle error when loading module actions
  example/repos/modules/module_test.sh
  src/actions/lay.go
  src/infra/error.go
  src/infra/infra.go
  src/infra/module.go
Labels: bug, enhancement

#117 Fix/dependency enrich error
  README.md
  docs/development/get_started.md
  example/exeiac.yml
  example/repos/infra-users/1-monitoring/1-bastion/brick.yml
  example/repos/infra-users/1-monitoring/1-grafana/brick.yml
  example/repos/infra-users/1-production/1-bastion/brick.yml
  example/repos/infra-users/1-production/1-cluster_k8s/brick.yml
  example/repos/infra-users/1-production/1-database/brick.yml
  example/repos/infra-users/1-staging/1-bastion/brick.yml
  example/repos/infra-users/1-staging/1-cluster_k8s/brick.yml
  example/repos/infra-users/1-staging/1-database/brick.yml
  src/arguments/arguments.go
  src/arguments/configuration.go
  src/arguments/flags.go
  src/infra/brick.go
  src/infra/infra.go
Labels: bug

#120 fix: fix an issue from previous rebase on refactoring
  src/arguments/configuration.go
Labels: bug
